import jsPDF from "jspdf";

interface Optimization {
  professional_summary: string | null;
  improved_bullets: { original: string; improved: string }[] | null;
  skills_to_add: string[] | null;
  missing_keywords: string[] | null;
  ats_score: number | null;
}

export function downloadResumePdf(opt: Optimization, filename = "tailored-resume.pdf") {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const margin = 56;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const addSpacer = (h = 14) => { y += h; };
  const checkPage = (needed = 20) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const heading = (text: string) => {
    checkPage(28);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(20, 110, 80);
    doc.text(text.toUpperCase(), margin, y);
    y += 6;
    doc.setDrawColor(20, 110, 80);
    doc.setLineWidth(1);
    doc.line(margin, y, pageWidth - margin, y);
    y += 14;
    doc.setTextColor(30, 30, 30);
  };

  const body = (text: string) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    const lines = doc.splitTextToSize(text, maxWidth);
    lines.forEach((line: string) => {
      checkPage(16);
      doc.text(line, margin, y);
      y += 14;
    });
  };

  const bullet = (text: string) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    const lines = doc.splitTextToSize(text, maxWidth - 14);
    lines.forEach((line: string, i: number) => {
      checkPage(16);
      if (i === 0) doc.text("•", margin, y);
      doc.text(line, margin + 14, y);
      y += 14;
    });
  };

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(15, 50, 40);
  doc.text("Tailored Resume", margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(110, 110, 110);
  doc.text(`Generated by Resume Tailor AI · ATS Match Score: ${opt.ats_score ?? "—"}/100`, margin, y + 12);
  y += 28;

  if (opt.professional_summary) {
    heading("Professional Summary");
    body(opt.professional_summary);
    addSpacer();
  }

  if (opt.improved_bullets && opt.improved_bullets.length) {
    heading("Improved Experience Bullets");
    opt.improved_bullets.forEach((b) => {
      bullet(b.improved);
      y += 2;
    });
    addSpacer();
  }

  if (opt.skills_to_add && opt.skills_to_add.length) {
    heading("Key Skills");
    body(opt.skills_to_add.join(" · "));
    addSpacer();
  }

  if (opt.missing_keywords && opt.missing_keywords.length) {
    heading("Keywords Incorporated");
    body(opt.missing_keywords.join(", "));
  }

  doc.save(filename);
}
